services:
  app:
    build: .
    environment:
      DB_BACKEND: sqlite
      CONNECTION_STRING: "sqlite:////code/database.db"
      DASHBOARD_PORT: 8080
    volumes:
      - ./main.db:/code/database.db
    ports:
      - 8082:8080
