services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./config/pg-init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-p 5432"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 40s
      start_interval: 1s
    shm_size: 128mb
    restart: "unless-stopped"

  broker:
    image: rabbitmq:management
    environment:
      RABBITMQ_NODE_PORT: 5672
      RABBITMQ_USE_LONGNAME: false
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 40s
      start_interval: 1s
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  migrations:
    build:
      dockerfile: ./migrations.Dockerfile
    environment:
      WALLET_DB_URL: "postgresql+psycopg://postgres@database/wallet"
      ANALYTIC_DB_URL: "postgresql+psycopg://postgres@database/analytic"
    depends_on:
      database:
        condition: service_healthy

  wallet:
    build:
      dockerfile: ./wallet-api.Dockerfile
    environment:
      DB_URL: "postgresql+psycopg://postgres@database/wallet"
      NOTIFICATION_QUEUE: "notification.router.queue"
      BROKER_URL: "amqp://guest:guest@broker:5672/?heartbeat=60"
    command: ["--port", "80"]
    volumes:
      - ./wallet.db:/code/wallet.db
    depends_on:
      migrations:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
    restart: "unless-stopped"

  router:
    build:
      dockerfile: ./event-engine.Dockerfile
      target: router
    environment:
      BROKER_URL: "amqp://guest:guest@broker:5672/?heartbeat=60"
      NOTIFICATION_QUEUE: "notification.router.queue"
      YOC_QUEUE: "processor.yoc.queue"
    depends_on:
      broker:
        condition: service_healthy
    restart: "unless-stopped"

  yoc:
    build:
      dockerfile: ./event-engine.Dockerfile
      target: yoc-processor
    environment:
      BROKER_URL: "amqp://guest:guest@broker:5672/?heartbeat=60"
      YOC_QUEUE: "processor.yoc.queue"
      WALLET_DB_URL: "postgresql+psycopg://postgres@database/wallet"
      ANALYTIC_DB_URL: "postgresql+psycopg://postgres@database/analytic"
    depends_on:
      broker:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: "unless-stopped"


networks:
  default:
    name: invest-earnings-network
    ipam:
      config:
        - subnet: 172.28.28.0/24
