services:
  app:
    build: .
    environment:
      DB_BACKEND: sqlite
      DB_BACKUP_PATH: /code/backups
      DB_BOOTSTRAP_DATA_PATH: /code/data/bootstrap/
      CONNECTION_STRING: "sqlite:////code/database.db"
      DASHBOARD_PORT: 8080
    ports:
      - 8082:8080
