"""Create initial database

Revision ID: 62d263ca3271
Revises: 
Create Date: 2025-05-08 10:19:47.468883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d263ca3271'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('b3_code', sa.String(), nullable=False, comment='Código de negociação na B3.'),
    sa.Column('name', sa.String(), nullable=False, comment='Nome do ativo.'),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('stock', 'bdr', 'fii', 'etf', name='assetkind'), nullable=False, comment='Tipo do ativo.'),
    sa.Column('added', sa.Date(), nullable=False, comment='Data de criação/cadastro do ativo no sistema.'),
    sa.PrimaryKeyConstraint('b3_code')
    )
    op.create_index(op.f('ix_asset_kind'), 'asset', ['kind'], unique=False)
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=True)
    op.create_table('earning',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='ID automático de provento.'),
    sa.Column('asset_b3_code', sa.String(), nullable=False),
    sa.Column('hold_date', sa.Date(), nullable=False, comment='Data de custódia.'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Data de pagamento.'),
    sa.Column('value_per_share', sa.Numeric(precision=10, scale=5, asdecimal=False), nullable=True, comment='Valor por unidade.'),
    sa.Column('ir_percentage', sa.Float(), nullable=True, comment='Taxa (%) de incidência do Imposto de Renda.'),
    sa.Column('kind', sa.Enum('dividend', 'jscp', 'taxable', name='earningkind'), nullable=False, comment='Tipo do provento.'),
    sa.ForeignKeyConstraint(['asset_b3_code'], ['asset.b3_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earning_kind'), 'earning', ['kind'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='ID automático da transação.'),
    sa.Column('asset_b3_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Data da transação.'),
    sa.Column('kind', sa.Enum('buy', 'sell', name='transactionkind'), nullable=False, comment='Tipo da transação.'),
    sa.Column('value_per_share', sa.Numeric(precision=10, scale=5, asdecimal=False), nullable=True, comment='Valor por unidade.'),
    sa.Column('shares', sa.Integer(), nullable=False, comment='Unidades movimentadas.'),
    sa.ForeignKeyConstraint(['asset_b3_code'], ['asset.b3_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_kind'), 'transaction', ['kind'], unique=False)
    op.create_table('earnings_rights',
    sa.Column('earning', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('has_right', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['earning'], ['earning.id'], ),
    sa.ForeignKeyConstraint(['has_right'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('earning', 'has_right')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings_rights')
    op.drop_index(op.f('ix_transaction_kind'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_earning_kind'), table_name='earning')
    op.drop_table('earning')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_index(op.f('ix_asset_kind'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
