"""Add market_price table

Revision ID: 46a9307fcdbf
Revises: a64e6d3b778d
Create Date: 2025-06-26 09:12:08.751267

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46a9307fcdbf"
down_revision: Union[str, None] = "a64e6d3b778d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_price",
        sa.Column(
            "reference_date",
            sa.Date(),
            nullable=False,
            comment="Data de referência dos dados.",
        ),
        sa.Column(
            "asset_b3_code",
            sa.String(),
            nullable=False,
            comment="Ativo sobre o qual esse dado se refere.",
        ),
        sa.Column(
            "closing_price",
            sa.Numeric(precision=10, scale=5, asdecimal=False),
            nullable=False,
            comment="Cota de fechamento na data de referência.",
        ),
        sa.ForeignKeyConstraint(
            ["asset_b3_code"], ["asset.b3_code"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("reference_date", "asset_b3_code"),
    )
    op.create_index(
        op.f("ix_market_price_reference_date"),
        "market_price",
        ["reference_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_price_reference_date"), table_name="market_price")
    op.drop_table("market_price")
    # ### end Alembic commands ###
