"""Update table economic_data with reference_month -> reference_date

Revision ID: a64e6d3b778d
Revises: f303d29a08c1
Create Date: 2025-05-09 12:01:21.539757

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a64e6d3b778d"
down_revision: Union[str, None] = "f303d29a08c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_data",
        sa.Column(
            "index",
            sa.Enum("cdi", "ipca", "ima_b", "ima_b_5plus", name="economicindex"),
            nullable=False,
            comment="Indíce ecônomico que os dados se referem.",
        ),
        sa.Column(
            "reference_date", sa.Date(), nullable=False, comment="Data de referência."
        ),
        sa.Column(
            "percentage_change",
            sa.Numeric(),
            nullable=False,
            comment="Variação do indicador para o mês de referência.",
        ),
        sa.Column(
            "number_index",
            sa.Numeric(precision=12, scale=6),
            nullable=True,
            comment="Número índice (se disponível).",
        ),
        sa.PrimaryKeyConstraint("index", "reference_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("economic_data")
    # ### end Alembic commands ###
