"""Add CASCADE to EarningsRights table

Revision ID: b756275b3369
Revises: 46a9307fcdbf
Create Date: 2025-07-02 12:29:45.203614

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b756275b3369"
down_revision: Union[str, None] = "46a9307fcdbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "earnings_rights_earning_fkey", "earnings_rights", type_="foreignkey"
    )
    op.drop_constraint(
        "earnings_rights_has_right_fkey", "earnings_rights", type_="foreignkey"
    )
    op.create_foreign_key(
        "earnings_rights_has_right_fkey",
        "earnings_rights",
        "transaction",
        ["has_right"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "earnings_rights_earning_fkey",
        "earnings_rights",
        "earning",
        ["earning"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "earnings_rights_earning_fkey", "earnings_rights", type_="foreignkey"
    )
    op.drop_constraint(
        "earnings_rights_has_right_fkey", "earnings_rights", type_="foreignkey"
    )
    op.create_foreign_key(
        "earnings_rights_earning_fkey",
        "earnings_rights",
        "earning",
        ["earning"],
        ["id"],
    )
    op.create_foreign_key(
        "earnings_rights_has_right_fkey",
        "earnings_rights",
        "transaction",
        ["has_right"],
        ["id"],
    )
    # ### end Alembic commands ###
