"""Add table economic_data

!!WARNING!! This migration contains
no information due to a mistake. In
order to remove it, the current databases
would have to be manually updated on the
alembic-related tables.

Revision ID: f303d29a08c1
Revises: 62d263ca3271
Create Date: 2025-05-09 11:31:10.143235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f303d29a08c1"
down_revision: Union[str, None] = "62d263ca3271"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
