"""Initial database

Revision ID: 6f219c0bf033
Revises:
Create Date: 2025-06-17 20:31:14.430557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f219c0bf033"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earning_yield",
        sa.Column(
            "b3_code", sa.String(), nullable=False, comment="Código B3 do ativo."
        ),
        sa.Column(
            "asset_kind",
            sa.Enum("stock", "bdr", "fii", "etf", name="assetkind"),
            nullable=False,
            comment="Tipo do ativo.",
        ),
        sa.Column(
            "earning_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="ID automático de provento.",
        ),
        sa.Column(
            "earning_kind",
            sa.Enum("dividend", "jscp", "taxable", name="earningkind"),
            nullable=False,
            comment="Tipo do provento.",
        ),
        sa.Column("hold_date", sa.Date(), nullable=False, comment="Data de custódia."),
        sa.Column(
            "payment_date", sa.Date(), nullable=False, comment="Data de pagamento."
        ),
        sa.Column(
            "ir",
            sa.Float(),
            nullable=False,
            comment="Taxa (%) de incidência do Imposto de Renda.",
        ),
        sa.Column(
            "value_per_share",
            sa.Numeric(precision=10, scale=5, asdecimal=False),
            nullable=True,
            comment="Valor do provento por unidade.",
        ),
        sa.Column(
            "ir_adjusted_value_per_share",
            sa.Numeric(precision=10, scale=5, asdecimal=False),
            nullable=True,
            comment="Valor líquido do provento por unidade.",
        ),
        sa.Column(
            "shares",
            sa.Integer(),
            nullable=False,
            comment="Quantidade de unidades do ativo na data de custódia.",
        ),
        sa.Column(
            "avg_price",
            sa.Numeric(precision=10, scale=5, asdecimal=False),
            nullable=True,
            comment="Preço médio pago pelo ativo na data de custódia.",
        ),
        sa.Column(
            "yoc",
            sa.Numeric(precision=10, scale=5, asdecimal=False),
            nullable=True,
            comment="Yield On Cost (YoC) com relação ao preço médio.",
        ),
        sa.Column(
            "cdi_on_hold_month",
            sa.Numeric(),
            nullable=False,
            comment="Variação do CDI no mês da data de custódia.",
        ),
        sa.Column(
            "ipca_on_hold_month",
            sa.Numeric(),
            nullable=False,
            comment="Variação do CDI no mês da data de custódia.",
        ),
        sa.PrimaryKeyConstraint("earning_id"),
    )
    op.create_index(
        op.f("ix_earning_yield_asset_kind"),
        "earning_yield",
        ["asset_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earning_yield_b3_code"), "earning_yield", ["b3_code"], unique=False
    )
    op.create_index(
        op.f("ix_earning_yield_earning_kind"),
        "earning_yield",
        ["earning_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earning_yield_hold_date"), "earning_yield", ["hold_date"], unique=False
    )
    op.create_index(
        op.f("ix_earning_yield_payment_date"),
        "earning_yield",
        ["payment_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_earning_yield_payment_date"), table_name="earning_yield")
    op.drop_index(op.f("ix_earning_yield_hold_date"), table_name="earning_yield")
    op.drop_index(op.f("ix_earning_yield_earning_kind"), table_name="earning_yield")
    op.drop_index(op.f("ix_earning_yield_b3_code"), table_name="earning_yield")
    op.drop_index(op.f("ix_earning_yield_asset_kind"), table_name="earning_yield")
    op.drop_table("earning_yield")
    # ### end Alembic commands ###
