"""Add total_earnings to earning_yield

Revision ID: 70ba2da21ca1
Revises: 6f219c0bf033
Create Date: 2025-06-20 20:25:00.653984

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70ba2da21ca1"
down_revision: Union[str, None] = "6f219c0bf033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "earning_yield",
        sa.Column(
            "total_earnings",
            sa.Numeric(precision=10, scale=5, asdecimal=False),
            nullable=True,
            comment="Total a ser recebido na data de pagamento.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("earning_yield", "total_earnings")
    # ### end Alembic commands ###
